export enum TypesSvgIcons {
    AMAZON_AWS              = 'amazonaws',
    CHESSKNIGHT             = 'chess-knight',
    CSS_ICON                = 'css3',
    FACEBOOK_ICON           = 'facebook',
    GITHUB_ICON             = 'github',
    GMAIL_ICON              = 'gmail',
    GRAPHQL                 = 'graphql',
    HOME_QUESTION           = 'home-question',
    JAVASCRIPT_ICON         = 'javascript',
    LINKEDIN_ICON           = 'linkedin',
    LINUX_ICON              = 'linux',
    MYSQL_ICON              = 'mysql',
    NESTJS_ICON             = 'nestjs',
    NEXTJS_ICON             = 'nextdotjs',
    PYTHON_ICON             = 'python',
    REACT_ICON              = 'react',
    REACTQUERY_ICON         = 'reactquery',
    SCRIPT_ICON             = 'script',
    SEMANTIC_WEB_ICON       = 'semantic-web',
    SPRINGBOOT_ICON         = 'springboot',
    TAILWIND_ICON           = 'tailwindcss',
    TERMINAL_ICON           = 'gnometerminal',
    TOOLS_ICON              = 'tools',
    VIEWDASHBOARD_ICON      = 'view-dashboard-edit',
    ADMIN_ICON              = 'account-tie',
}