import { TypesSvgIcons } from "../enums/typesSvgIcons";
import { DescriptionIcons } from "../definitions/typeDescriptionIcons";

export const DESCRIPCION_ICONS: DescriptionIcons = {
    [TypesSvgIcons.REACT_ICON]          : "React",
    [TypesSvgIcons.CSS_ICON]            : "Css",
    [TypesSvgIcons.TAILWIND_ICON]       : "Tailwind",
    [TypesSvgIcons.AMAZON_AWS]          : "AWS",
    [TypesSvgIcons.CHESSKNIGHT]         : "",
    [TypesSvgIcons.FACEBOOK_ICON]       : "Facebook",
    [TypesSvgIcons.GITHUB_ICON]         : "Github",
    [TypesSvgIcons.GMAIL_ICON]          : "Gmail",
    [TypesSvgIcons.GRAPHQL]             : "Graphql",
    [TypesSvgIcons.HOME_QUESTION]       : "",
    [TypesSvgIcons.JAVASCRIPT_ICON]     : "Javascript",
    [TypesSvgIcons.LINKEDIN_ICON]       : "Linkedin",
    [TypesSvgIcons.LINUX_ICON]          : "Linux",
    [TypesSvgIcons.MYSQL_ICON]          : "Mysql",
    [TypesSvgIcons.NESTJS_ICON]         : "Nestjs",
    [TypesSvgIcons.NEXTJS_ICON]         : "Nextjs",
    [TypesSvgIcons.PYTHON_ICON]         : "Python",
    [TypesSvgIcons.REACTQUERY_ICON]     : "React Query",
    [TypesSvgIcons.SCRIPT_ICON]         : "Script",
    [TypesSvgIcons.SEMANTIC_WEB_ICON]   : "Semantic web",
    [TypesSvgIcons.SPRINGBOOT_ICON]     : "Spring boot",
    [TypesSvgIcons.TERMINAL_ICON]       : "Terminal",
    [TypesSvgIcons.TOOLS_ICON]          : "Tools",
    [TypesSvgIcons.VIEWDASHBOARD_ICON]  : "ViewDashboard",
    [TypesSvgIcons.ADMIN_ICON]          : "Admin",
    [TypesSvgIcons.NODEDOT_JS]          : "NodeJs",
    [TypesSvgIcons.JAVA]                : "Java",
    [TypesSvgIcons.WEBSOCKET]           : "Websocket",
    [TypesSvgIcons.API]                 : "API",
    [TypesSvgIcons.NEO4J]               : "Neo4j",
    [TypesSvgIcons.SUPABASE]            : "supabase",
    [TypesSvgIcons.TYPESCRIPT]          : "Typescript",
    [TypesSvgIcons.JSONWEBTOKEN]        : "Json Web Token",
    [TypesSvgIcons.LEAFLET]             : "leaflet",
    [TypesSvgIcons.SEQUELIZE]           : "sequelize",
    [TypesSvgIcons.EJS]                 : "ejs"
};